apiVersion: v1
kind: Secret
metadata:
  name: {{ include "collector.fullname" . }}
  labels:
    {{- include "collector.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
